import Navbar from "./components/Navbar";
import { CourseIdProvider } from "@/app/providers/CourseIdProvider";
import "./globals.css";

export const metadata = {
  title: "Writing Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CourseIdProvider>
      <html lang="en">
        <body className="antialiased">
          <Navbar />
          {children}
        </body>
      </html>
    </CourseIdProvider>
  );
}
