import Navbar from "./components/Navbar";
import { CourseIdProvider } from "@/app/providers/CourseIdProvider";
import Script from "next/script";
import "./globals.css";

export const metadata = {
  title: "Writing Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CourseIdProvider>
      <html lang="en">
        <head>
          <Script
            src={`${process.env.NEXT_PUBLIC_BASE_PATH || ""}/runtime-config.js`}
            strategy="beforeInteractive"
          />
        </head>
        <body className="antialiased">
          <Navbar />
          {children}
        </body>
      </html>
    </CourseIdProvider>
  );
}
