export const students = [
  {
    id: 1,
    name: "Robert Fox",
    period: "Period 1A",
    avgScore: 85.3,
    essays: 12,
    mostImproved: "Grammar",
    avatar: "RF",
    gender: "Male",
    age: 17,
    class: "1A",
    missingDays: 0,
  },
  {
    id: 2,
    name: "Marvin McKinney",
    period: "Period 1B",
    avgScore: 92.1,
    essays: 15,
    mostImproved: "Argumentation",
    avatar: "MM",
    gender: "Male",
    age: 6,
    class: "1B",
    missingDays: 0,
  },
  {
    id: 3,
    name: "Darrell Steward",
    period: "Period 4C",
    avgScore: 78.9,
    essays: 8,
    mostImproved: "Structure",
    avatar: "DS",
    gender: "Female",
    age: 10,
    class: "4C",
    missingDays: 6,
  },
  {
    id: 4,
    name: "Savannah Nguyen",
    period: "Period 4C",
    avgScore: 88.7,
    essays: 11,
    mostImproved: "Transitions",
    avatar: "SN",
    gender: "Male",
    age: 11,
    class: "4C",
    missingDays: 6,
  },
  {
    id: 5,
    name: "Dianne Russell",
    period: "Period 11B",
    avgScore: 91.2,
    essays: 14,
    mostImproved: "Grammar",
    avatar: "DR",
    gender: "Female",
    age: 16,
    class: "11B",
    missingDays: 10,
  },
  {
    id: 6,
    name: "Cody Fisher",
    period: "Period 4A",
    avgScore: 82.4,
    essays: 9,
    mostImproved: "Structure",
    avatar: "CF",
    gender: "Female",
    age: 11,
    class: "4A",
    missingDays: 20,
  },
  {
    id: 7,
    name: "Leslie Alexander",
    period: "Period 5A",
    avgScore: 87.6,
    essays: 13,
    mostImproved: "Argumentation",
    avatar: "LA",
    gender: "Female",
    age: 12,
    class: "5A",
    missingDays: 0,
  },
  {
    id: 8,
    name: "Albert Flores",
    period: "Period 7B",
    avgScore: 84.1,
    essays: 10,
    mostImproved: "Grammar",
    avatar: "AF",
    gender: "Male",
    age: 14,
    class: "7B",
    missingDays: 0,
  },
  {
    id: 9,
    name: "Ralph Edwards",
    period: "Period 11C",
    avgScore: 89.5,
    essays: 16,
    mostImproved: "Transitions",
    avatar: "RE",
    gender: "Male",
    age: 17,
    class: "11C",
    missingDays: 1,
  },
  {
    id: 10,
    name: "Darlene Robertson",
    period: "Period 1A",
    avgScore: 86.8,
    essays: 12,
    mostImproved: "Structure",
    avatar: "DR",
    gender: "Female",
    age: 18,
    class: "1A",
    missingDays: 0,
  },
];

export const assignments = [
  {
    id: 1,
    title: "Persuasive Essay",
    submissions: "26/28",
    avgScore: 84.3,
    dueDate: "May 12",
    status: "Graded",
    statusColor: "text-green-600 bg-green-50",
  },
  {
    id: 2,
    title: "Book Report #2",
    submissions: "22/28",
    avgScore: 79.6,
    dueDate: "May 5",
    status: "Grading",
    statusColor: "text-orange-600 bg-orange-50",
  },
  {
    id: 3,
    title: "Poetry Analysis",
    submissions: "28/28",
    avgScore: 88.9,
    dueDate: "Apr 30",
    status: "Graded",
    statusColor: "text-green-600 bg-green-50",
  },
  {
    id: 4,
    title: "Research Paper Draft",
    submissions: "18/28",
    avgScore: 76.2,
    dueDate: "May 20",
    status: "Open",
    statusColor: "text-blue-600 bg-blue-50",
  },
  {
    id: 5,
    title: "Creative Writing",
    submissions: "24/28",
    avgScore: 91.4,
    dueDate: "Apr 25",
    status: "Graded",
    statusColor: "text-green-600 bg-green-50",
  },
  {
    id: 6,
    title: "Compare & Contrast Essay",
    submissions: "28/28",
    avgScore: 82.7,
    dueDate: "Apr 15",
    status: "Graded",
    statusColor: "text-green-600 bg-green-50",
  },
];

export const baseTags = [
  "Argumentative",
  "Narrative",
  "Personal",
  "Analytical",
  "Reflective",
  "Opinion",
  "Education",
  "Descriptive",
  "Experience",
  "Economics",
  "Research",
];

// genre colors for shading
export const GENRE_COLORS = {
  Argumentative: "#ecfccb",
  Narrative: "#e0e7ff",
  Analytical: "#e0f2fe",
  Reflective: "#fae8ff",
  Descriptive: "#fef9c3",
  Personal: "#fef3c7",
  Opinion: "#f5f5f5",
  Education: "#f0fdf4",
  Experience: "#fff1f2",
  Economics: "#eef2ff",
  Research: "#f1f5f9",
};

// ---- Metric definitions (adds longPauseRatioPct + clearer labels) ----
export const METRIC_DEFS = [
  // PRODUCT
  {
    key: "wordCount",
    label: "Word Count",
    category: "Product",
    unit: "words",
    get: (e) => e.words,
  },
  {
    key: "uniqueWords",
    label: "Unique Words",
    category: "Product",
    unit: "words",
    get: (e) => e.uniqueWords,
  },
  {
    key: "lexicalDiversity",
    label: "Lexical Diversity",
    category: "Product",
    unit: "%",
    get: (e) => e.lexicalDiversity,
  },
  {
    key: "avgSentenceLen",
    label: "Avg Sentence Length",
    category: "Product",
    unit: "words/sent",
    get: (e) => e.avgSentenceLen,
  },
  // PROCESS
  {
    key: "wpm",
    label: "Fluency (WPM in bursts)",
    category: "Process",
    unit: "wpm",
    get: (e) => e.wpm,
  },
  {
    key: "burst",
    label: "Burst Length",
    category: "Process",
    unit: "words",
    get: (e) => Math.max(1, Math.round(e.burst / 1)),
  },
  {
    key: "avgPauseSec",
    label: "Avg Pause (sec)",
    category: "Process",
    unit: "sec",
    get: (e) => e.avgPauseSec,
  },
  {
    key: "longPauseRatioPct",
    label: "Long-Pause Ratio (%)",
    category: "Process",
    unit: "%",
    get: (e) => {
      const total = Math.max(1, e.pauses + e.longPauses);
      return Number(((e.longPauses / total) * 100).toFixed(1));
    },
  },
  // REVISION
  {
    key: "revisionDepth",
    label: "Revision Depth (count)",
    category: "Revision",
    unit: "revisions",
    get: (e) => e.revisionDepth,
  },
  {
    key: "deletions",
    label: "Deletions",
    category: "Revision",
    unit: "ops",
    get: (e) => e.deletions,
  },
  {
    key: "insertions",
    label: "Insertions",
    category: "Revision",
    unit: "ops",
    get: (e) => e.insertions,
  },
  {
    key: "editRatioPct",
    label: "Revision Density (% per 100 words)",
    category: "Revision",
    unit: "%",
    get: (e) => e.editRatioPct,
  },
  // OUTCOME
  {
    key: "gradePct",
    label: "Grade (%)",
    category: "Quality",
    unit: "%",
    get: (e) => gradeToPct(e.grade),
  },
];

export const metricSections = [
  {
    name: "Product Metrics",
    keys: ["wordCount", "uniqueWords", "lexicalDiversity", "avgSentenceLen"],
  },
  {
    name: "Process Metrics",
    keys: ["wpm", "burst", "avgPauseSec", "longPauseRatioPct"],
  },
  {
    name: "Revision Metrics",
    keys: ["revisionDepth", "deletions", "insertions", "editRatioPct"],
  },
  { name: "Quality & Outcomes", keys: ["gradePct"] },
];

export const DEFAULT_METRICS = [
  "wpm",
  "longPauseRatioPct",
  "burst",
  "editRatioPct",
  "gradePct",
];

const gradeToPct = (g) => {
  const map = {
    "A+": 97,
    A: 94,
    "A-": 91,
    "B+": 88,
    B: 85,
    "B-": 82,
    "C+": 78,
    C: 75,
    "C-": 72,
  };
  return map[g] ?? 80;
};